### ISSUE TITLE
Zero Pressure Event (ZPE) is triggering while idle

### ISSUE THREAD

**Issue by eprast22** [eprast22/iForce#1]
Without movement the sensor is seeing a residual force value and registering ZPE prompts incorrectly.
Solution: Use acceleration to check for movement before increasing the count to 50 steps to trigger a ZPE.

**Comment by eprast22** [comment]
Magnus said that ZPE should not be triggering without any pressure. The algorithm for ZPE should analyze a specific number of steps (based on acceleration) with 0.3 lbs pressure or less and if the step threshold is exceeded it will trigger a ZPE. 

For example if walking 25 steps out of 100 (or more) with no distal pressure (0.3 lbs or less) a notification will be triggered to the user to Remove socks. 

Please confirm this is how the algorithm works!

**Comment by pandasoft0** [comment]
Yes, confirmed. App analyzes xx steps and if yy steps have pressure below zz lbs - fire an event.

**Comment by eprast22** [comment]
ZPE Event is working for now. Closing issue.
