### ISSUE TITLE
Good Fit Notification criteria

### ISSUE THREAD

**Issue by eprast22** [eprast22/iForce#8]
Need a better a definition of how and when Good Fit is issued. 

Further testing showed Good Fit in between PMP notifications during the same activity. Good fit is defined as: Good Fit should still be recorded every time an integration period finishes and there is no
prompt recorded. The number of good fits should be totalled daily and send with the
Daily Report.

**Comment by pandasoft0** [comment]
App will fire good fit events only if time elapsed from any last event > Integration Time and patient made at least one step after. I made these changes in the last version. Please check.

**Comment by eprast22** [comment]
Ok thanks for clarifying this. Closing issue.
